name: burt
description: A new Flutter project to manage cars.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.0
  google_sign_in: ^6.0.2
  cloud_firestore: ^4.7.0
  provider: ^6.1.0
  intl: ^0.18.0
  encrypt: ^5.0.3
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/illustrations/
    - assets/icons/
