name: burt
description: A new Flutter project to manage cars.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.0
  google_sign_in: ^6.0.2
  cloud_firestore: ^4.7.0
  flutter_local_notifications: ^13.0.0
  provider: ^6.1.0
  intl: ^0.18.0
  flutter_svg: ^1.0.3
  line_icons: ^2.0.1
  google_fonts: ^4.0.4
  flutter_animated_icons: ^1.0.1
  syncfusion_flutter_charts: ^26.1.42

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
